# Generated by Django 6.0.2 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username_last_changed",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Остання зміна нікнейму"),
        ),
    ]
