# Generated by Django 6.0.2 on 2026-02-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_username_last_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="theme_preference",
            field=models.CharField(
                choices=[("dark", "Dark"), ("light", "Light")],
                default="dark",
                max_length=10,
                verbose_name="Тема",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="accent_preference",
            field=models.CharField(
                default="default",
                max_length=12,
                verbose_name="Акцент",
            ),
        ),
    ]
